postgresql_username = "sonar"
postgresql_password = "securepassword123"
postgresql_database = "sonarqube"
sonarqube_monitoring_passcode = "securepassword123"
postgresql_server = "postgresql.default.svc.cluster.local"